import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

const listLanguagesMock = vi.fn();
const fetchTranscriptMock = vi.fn();

vi.mock('youtube-transcript-plus', () => {
  class YoutubeTranscriptTooManyRequestError extends Error {}
  class YoutubeTranscriptVideoUnavailableError extends Error {
    constructor(readonly videoId: string) {
      super('video unavailable');
    }
  }
  class YoutubeTranscriptDisabledError extends Error {
    constructor(readonly videoId: string) {
      super('disabled');
    }
  }
  class YoutubeTranscriptNotAvailableError extends Error {
    constructor(readonly videoId: string) {
      super('not available');
    }
  }
  class YoutubeTranscriptNotAvailableLanguageError extends Error {
    constructor(
      readonly lang: string,
      readonly availableLangs: string[],
      readonly videoId: string
    ) {
      super('language unavailable');
    }
  }
  class YoutubeTranscriptInvalidLangError extends Error {
    constructor(readonly lang: string) {
      super('invalid lang');
    }
  }
  class YoutubeTranscriptInvalidVideoIdError extends Error {}

  return {
    FsCache: class FsCache {},
    fetchTranscript: fetchTranscriptMock,
    listLanguages: listLanguagesMock,
    YoutubeTranscriptTooManyRequestError,
    YoutubeTranscriptVideoUnavailableError,
    YoutubeTranscriptDisabledError,
    YoutubeTranscriptNotAvailableError,
    YoutubeTranscriptNotAvailableLanguageError,
    YoutubeTranscriptInvalidLangError,
    YoutubeTranscriptInvalidVideoIdError
  };
});

describe('api routes', () => {
  let server: Awaited<ReturnType<typeof startServer>>;

  beforeEach(async () => {
    vi.resetModules();
    listLanguagesMock.mockReset();
    fetchTranscriptMock.mockReset();
    vi.stubEnv('OPENAI_API_KEY', '');
    vi.stubEnv('DATA_DIR', '');

    const { createApp } = await import('../server/index');
    server = await startServer(createApp());
  });

  afterEach(async () => {
    await new Promise<void>((resolve) => server.instance.close(() => resolve()));
    vi.unstubAllEnvs();
    vi.unstubAllGlobals();
  });

  it('returns normalized transcript data', async () => {
    listLanguagesMock.mockResolvedValue([
      { languageCode: 'en', languageName: 'English', isAutoGenerated: true }
    ]);
    fetchTranscriptMock.mockResolvedValue({
      videoDetails: {
        videoId: 'dQw4w9WgXcQ',
        title: 'Demo',
        author: 'Channel',
        lengthSeconds: 60,
        thumbnails: []
      },
      segments: [{ offset: 1, duration: 2, text: 'Hello &amp; welcome', lang: 'en' }]
    });

    const response = await fetch(`${server.url}/api/transcript`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ url: 'https://youtu.be/dQw4w9WgXcQ' })
    });
    const json = await response.json();

    expect(response.status).toBe(200);
    expect(json.videoId).toBe('dQw4w9WgXcQ');
    expect(json.segments[0]).toMatchObject({
      startMs: 1000,
      durationMs: 2000,
      text: 'Hello & welcome'
    });
  });

  it('returns a clear translation configuration error', async () => {
    const response = await fetch(`${server.url}/api/translate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        videoId: 'dQw4w9WgXcQ',
        sourceLang: 'en',
        targetLang: 'zh-CN',
        segments: [{ id: 'a', startMs: 0, durationMs: 1000, text: 'Hello.' }]
      })
    });
    const json = await response.json();

    expect(response.status).toBe(400);
    expect(json.error.code).toBe('AI_NOT_CONFIGURED');
  });
});

async function startServer(app: import('express').Express) {
  const instance = app.listen(0, '127.0.0.1');
  await new Promise<void>((resolve) => instance.once('listening', () => resolve()));
  const address = instance.address();

  if (!address || typeof address === 'string') {
    throw new Error('Unable to bind test server');
  }

  return {
    instance,
    url: `http://127.0.0.1:${address.port}`
  };
}
