import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import App from '../src/App';
import type { TranscriptSegment } from '../shared/types';

type MockSeekCall = {
  seconds: number;
  allowSeekAhead: boolean;
};

class MockYouTubePlayer {
  currentTime = 0;
  duration = 20;
  playbackRate = 1;
  seekCalls: MockSeekCall[] = [];
  private options: {
    events?: {
      onReady?: (event: { target: MockYouTubePlayer }) => void;
      onStateChange?: (event: { target: MockYouTubePlayer; data: number }) => void;
    };
  };

  constructor(_element: HTMLElement, options: MockYouTubePlayer['options']) {
    this.options = options;
    activePlayer = this;
    queueMicrotask(() => this.options.events?.onReady?.({ target: this }));
  }

  playVideo() {
    this.options.events?.onStateChange?.({ target: this, data: 1 });
  }

  pauseVideo() {
    this.options.events?.onStateChange?.({ target: this, data: 2 });
  }

  seekTo(seconds: number, allowSeekAhead: boolean) {
    this.currentTime = seconds;
    this.seekCalls.push({ seconds, allowSeekAhead });
  }

  getCurrentTime() {
    return this.currentTime;
  }

  getDuration() {
    return this.duration;
  }

  setPlaybackRate(rate: number) {
    this.playbackRate = rate;
  }

  getPlaybackRate() {
    return this.playbackRate;
  }

  destroy() {}
}

let activePlayer: MockYouTubePlayer;
let transcriptSegments: TranscriptSegment[];
let translatedSegments: TranscriptSegment[];

async function loadDemoVideo() {
  await userEvent.click(screen.getByRole('button', { name: '载入' }));
  await userEvent.type(screen.getByLabelText('YouTube 链接'), 'https://youtu.be/dQw4w9WgXcQ');
  await userEvent.click(screen.getByRole('button', { name: '载入视频' }));
}

describe('App', () => {
  beforeEach(() => {
    transcriptSegments = [{ id: 'seg-0-0', startMs: 0, durationMs: 1000, text: 'Hello there.' }];
    translatedSegments = [{ ...transcriptSegments[0], translation: '你好。' }];

    vi.stubGlobal('YT', {
      Player: MockYouTubePlayer,
      PlayerState: {
        PLAYING: 1,
        PAUSED: 2,
        ENDED: 0
      }
    });
    vi.stubGlobal(
      'fetch',
      vi.fn(async (input: RequestInfo | URL) => {
        const url = String(input);

        if (url.endsWith('/api/library/videos')) {
          return Response.json({ items: [] });
        }

        if (url.endsWith('/api/library/lookup')) {
          return Response.json({ record: null });
        }

        if (url.endsWith('/api/transcript')) {
          return Response.json({
            videoId: 'dQw4w9WgXcQ',
            sourceLang: 'en',
            languages: [{ languageCode: 'en', languageName: 'English', isAutoGenerated: true }],
            video: {
              videoId: 'dQw4w9WgXcQ',
              title: 'Demo title',
              author: 'Demo channel',
              lengthSeconds: 60,
              thumbnails: []
            },
            segments: transcriptSegments
          });
        }

        if (url.endsWith('/api/translate')) {
          return Response.json({
            videoId: 'dQw4w9WgXcQ',
            sourceLang: 'en',
            targetLang: 'zh-CN',
            cacheHit: false,
            segments: translatedSegments
          });
        }

        return Response.json({ error: { code: 'NOT_FOUND', message: 'not found' } }, { status: 404 });
      })
    );
  });

  it('loads transcript and renders translated subtitles', async () => {
    render(<App />);

    await loadDemoVideo();

    expect((await screen.findAllByText('Hello there.')).length).toBeGreaterThanOrEqual(2);

    await waitFor(() => {
      expect(screen.getAllByText('你好。').length).toBeGreaterThanOrEqual(2);
    });
  });

  it('collapses and restores the transcript pane', async () => {
    render(<App />);

    expect(screen.getByRole('heading', { name: '双语字幕' })).toBeInTheDocument();

    await userEvent.click(screen.getByRole('button', { name: '收起' }));

    expect(screen.queryByRole('heading', { name: '双语字幕' })).not.toBeInTheDocument();

    await userEvent.click(screen.getByRole('button', { name: '字幕' }));

    expect(screen.getByRole('heading', { name: '双语字幕' })).toBeInTheDocument();
  });

  it('supports seek, sentence navigation, playback rate, and locked sentence loop', async () => {
    transcriptSegments = [
      { id: 'seg-0-0', startMs: 0, durationMs: 1000, text: 'First sentence.' },
      { id: 'seg-1-1000', startMs: 1000, durationMs: 1000, text: 'Second sentence.' }
    ];
    translatedSegments = [
      { ...transcriptSegments[0], translation: '第一句。' },
      { ...transcriptSegments[1], translation: '第二句。' }
    ];

    render(<App />);

    await loadDemoVideo();
    await waitFor(() => expect(screen.getByTitle('播放')).not.toBeDisabled());

    await userEvent.click(screen.getByTitle('下一句'));
    expect(activePlayer.seekCalls.at(-1)).toMatchObject({ seconds: 1, allowSeekAhead: true });

    await userEvent.click(screen.getByTitle('快进 5 秒'));
    await waitFor(() => expect(activePlayer.seekCalls.at(-1)).toMatchObject({ seconds: 6, allowSeekAhead: true }));

    await userEvent.click(screen.getByTitle('后退 5 秒'));
    await waitFor(() => expect(activePlayer.seekCalls.at(-1)).toMatchObject({ seconds: 1, allowSeekAhead: true }));

    await userEvent.selectOptions(screen.getByLabelText('倍速'), '1.5');
    expect(activePlayer.playbackRate).toBe(1.5);

    await userEvent.click(screen.getByTitle('上一句'));
    await waitFor(() => expect(activePlayer.seekCalls.at(-1)).toMatchObject({ seconds: 0, allowSeekAhead: true }));

    await userEvent.click(screen.getByTitle('下一句'));
    await waitFor(() => expect(activePlayer.seekCalls.at(-1)).toMatchObject({ seconds: 1, allowSeekAhead: true }));

    const loopButton = screen.getByTitle('单句循环');
    await userEvent.click(loopButton);
    expect(loopButton).toHaveAttribute('aria-pressed', 'true');
    expect(activePlayer.seekCalls.at(-1)).toMatchObject({ seconds: 1, allowSeekAhead: true });

    const loopSeekStart = activePlayer.seekCalls.length;
    activePlayer.currentTime = 2.2;

    await waitFor(() => {
      expect(activePlayer.seekCalls.slice(loopSeekStart).some((call) => call.seconds === 1)).toBe(true);
    });
  });
});
