import { FsCache, fetchTranscript, listLanguages } from 'youtube-transcript-plus';
import type { CaptionTrackInfo, TranscriptResult } from 'youtube-transcript-plus';
import { normalizeTranscriptSegments } from '../shared/transcript';
import type { CaptionLanguage, TranscriptPayload, VideoSummary } from '../shared/types';
import { extractYoutubeVideoId } from '../shared/youtube';
import { HttpError, toHttpError } from './httpError';
import { getDataPath } from './paths';

const transcriptCache = new FsCache(getDataPath('transcript-cache'), 24 * 60 * 60 * 1000);

export async function getTranscript(url: string, lang = 'en'): Promise<TranscriptPayload> {
  const videoId = extractYoutubeVideoId(url);

  if (!videoId) {
    throw new HttpError(400, 'INVALID_YOUTUBE_URL', '请粘贴有效的 YouTube 视频链接。');
  }

  try {
    const languages = await listLanguages(videoId, {
      cache: transcriptCache,
      retries: 2,
      retryDelay: 750
    });
    const sourceLang = chooseCaptionLanguage(languages, lang);

    const result = await fetchTranscript(videoId, {
      cache: transcriptCache,
      lang: sourceLang,
      retries: 2,
      retryDelay: 750,
      videoDetails: true
    });

    return {
      videoId,
      sourceLang,
      languages: languages.map(toCaptionLanguage),
      video: toVideoSummary((result as TranscriptResult).videoDetails),
      segments: normalizeTranscriptSegments((result as TranscriptResult).segments)
    };
  } catch (error) {
    throw toHttpError(error);
  }
}

export function chooseCaptionLanguage(languages: CaptionTrackInfo[], requestedLang: string): string {
  const normalizedRequest = requestedLang.trim().toLowerCase();
  const exact = languages.find((language) => language.languageCode.toLowerCase() === normalizedRequest);

  if (exact) {
    return exact.languageCode;
  }

  const sameBase = languages.find((language) => {
    const code = language.languageCode.toLowerCase();
    return code === normalizedRequest.split('-')[0] || code.startsWith(`${normalizedRequest}-`);
  });

  if (sameBase) {
    return sameBase.languageCode;
  }

  throw new HttpError(404, 'LANGUAGE_NOT_AVAILABLE', '这个视频没有英文字幕。', {
    availableLangs: languages.map((language) => language.languageCode)
  });
}

function toCaptionLanguage(language: CaptionTrackInfo): CaptionLanguage {
  return {
    languageCode: language.languageCode,
    languageName: language.languageName,
    isAutoGenerated: language.isAutoGenerated
  };
}

function toVideoSummary(videoDetails: TranscriptResult['videoDetails']): VideoSummary {
  return {
    videoId: videoDetails.videoId,
    title: videoDetails.title,
    author: videoDetails.author,
    lengthSeconds: videoDetails.lengthSeconds,
    thumbnails: videoDetails.thumbnails
  };
}
