export type CaptionLanguage = {
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
};

export type TranscriptSegment = {
  id: string;
  startMs: number;
  durationMs: number;
  text: string;
  translation?: string;
};

export type VideoSummary = {
  videoId: string;
  title: string;
  author: string;
  lengthSeconds: number;
  thumbnails: Array<{
    url: string;
    width: number;
    height: number;
  }>;
};

export type TranscriptPayload = {
  videoId: string;
  sourceLang: string;
  languages: CaptionLanguage[];
  video?: VideoSummary;
  segments: TranscriptSegment[];
};

export type StoredVideoRecord = TranscriptPayload & {
  url: string;
  createdAt: string;
  updatedAt: string;
  lastOpenedAt: string;
};

export type VideoHistoryItem = {
  videoId: string;
  url: string;
  title: string;
  author: string;
  thumbnailUrl?: string;
  sourceLang: string;
  segmentCount: number;
  translatedCount: number;
  createdAt: string;
  updatedAt: string;
  lastOpenedAt: string;
};

export type VideoHistoryPayload = {
  items: VideoHistoryItem[];
};

export type StoredVideoPayload = {
  record: StoredVideoRecord | null;
};

export type TranslationPayload = {
  videoId: string;
  sourceLang: string;
  targetLang: string;
  cacheHit: boolean;
  segments: TranscriptSegment[];
};

export type ApiErrorPayload = {
  error: {
    code: string;
    message: string;
    details?: unknown;
  };
};

export type TranslationStreamChunk = {
  type: 'chunk';
  videoId: string;
  sourceLang: string;
  targetLang: string;
  cacheHit: false;
  completed: number;
  total: number;
  segments: TranscriptSegment[];
};

export type TranslationStreamDone = {
  type: 'done';
  videoId: string;
  sourceLang: string;
  targetLang: string;
  cacheHit: boolean;
  completed: number;
  total: number;
  segments: TranscriptSegment[];
};

export type TranslationStreamError = {
  type: 'error';
  status: number;
  error: ApiErrorPayload['error'];
};

export type TranslationStreamEvent =
  | TranslationStreamChunk
  | TranslationStreamDone
  | TranslationStreamError;
